### ISSUE TITLE
请问区域类的数据怎么随机？

### ISSUE THREAD

**Issue by zouyn** [wujianqi/shai#2]
![image](https://user-images.githubusercontent.com/33949274/59399844-0f3ad400-8dc8-11e9-8fba-e1741955bd34.png)
![image](https://user-images.githubusercontent.com/33949274/59399868-224da400-8dc8-11e9-8b96-bc894bae2731.png)

接口想获取随机地区，请问怎么实现。

**Comment by wujianqi** [comment]
感谢提出问题。取消了实例化API导致这情况，已更新，请使用0.2.21版！
