### ISSUE TITLE
生成大量嵌套数据非常慢，疯狂吃内存

### ISSUE THREAD

**Issue by hy-inger** [wujianqi/shai#4]

**Comment by wujianqi** [comment]
以每组数据长度为15，嵌套3级，那么产生的记录是3615条；
以每组数据长度为20，嵌套4级，那么产生的记录是168420条；
以每组数据长度为15，嵌套5级，那么产生的记录是813615条；

每嵌套深1层，相当于增加1次”指数“。
现已优化，但总数据量越大越吃内存，这个避免不了。
